version: '2'
services:
    swhappy-postgresql:
        container_name: swhappy-postgresql
        image: postgres:9.5.4
        # volumes:
        #     - ~/volumes/jhipster/swhappy/postgresql/:/var/lib/postgresql/
        environment:
            - POSTGRES_USER=swhappy
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
